services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lnicolof/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lnicolof/data/wordpress

networks:
  inception:
    driver: bridge
